name: u_lg
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2025.1.31=hf0a4a13_0
  - libffi=3.4.2=h3422bc3_5
  - liblzma=5.6.4=h39f12f2_0
  - libsqlite=3.48.0=h3f77e49_1
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.4.0=h81ee809_1
  - pip=25.0=pyh8b19718_0
  - python=3.10.16=h870587a_1_cpython
  - readline=8.2=h92ec313_1
  - setuptools=75.8.0=pyhff2d567_0
  - tk=8.6.13=h5083fa2_1
  - tzdata=2025a=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.8.0
      - async-timeout==4.0.3
      - attrs==25.1.0
      - black==24.4.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - exceptiongroup==1.2.2
      - frozenlist==1.5.0
      - grandalf==0.8
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - isort==5.13.2
      - jiter==0.8.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.1.16
      - langchain-community==0.0.38
      - langchain-core==0.1.53
      - langchain-openai==0.1.3
      - langchain-text-splitters==0.0.2
      - langgraph==0.0.38
      - langsmith==0.1.147
      - marshmallow==3.26.1
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - numpy==1.26.4
      - openai==1.61.1
      - orjson==3.10.15
      - packaging==23.2
      - pathspec==0.12.1
      - platformdirs==4.3.6
      - propcache==0.2.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.2.1
      - python-dotenv==1.0.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.38
      - tenacity==8.5.0
      - tiktoken==0.8.0
      - tomli==2.2.1
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - urllib3==2.3.0
      - yarl==1.18.3
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/u_lg
